
theme: jekyll-theme-minimal
title: EEG Lab book
description: Lab book for running EEG experiments


baseurl: "/EEGLabBook"
destination: "./_site"
source: "."
plugins:
  - jekyll-feed
  - jekyll-seo-tag
